---
title: "The Near Word"
author: "Peter Hubbard"
date: "8/21/2016"
---

# The Near Word
#### Romans 10:5-21

## The word is near. (5-13)

### Why does Paul want us to know the word is near?

- Israel turned a *near* word into a <answer>BLANK BLANK</answer>. (1-4)
```
"For Christ is the end of the law for righteousness to everyone who believes." (10:4)
```
    - "End" =

- We can turn a newar words into a <answer>BLANK BLANK</answer>. (5-8)




What do we do?

- The <answer>BLANK</answer>

- <answer>BLANK</answer>

- Legalism - possible characteristics
    - You are more aware of your past sins than of the <answer>BLANK</answer>.
    - You live believing that God is <answer>BLANK</answer> with you.
    - You believe that forgiveness is dependent on your <answer>BLANK</answer>.
    - You lack <answer>BLANK</answer>.
    - You are willing to live with low-grade <answer>BLANK</answer> (or paralyzing condemnation) because you assume that it is <answer>BLANK</answer>.


- We experience the near word as we <answer>BLANK BLANK</answer>. (9-10)

- <answer>BLANK</answer> who believes will be <answer>BLANK</answer>. (11-13)


## The word goes far. (14-21)

- God sends His near word far through the <answer>BLANK</answer>

*"Sending implies on the one side a restriction, but on the other an enhancement, of the power of the herald.  The one who sends gives him the content of the messae and authority.  The disciples do not roclaime their own discoveries or insights....  A preacher is not a reporter who recounts his own eperiences.  He is the angent of someone higher whose will he loudly and clearly makes known to the public.  Without calling and sending, preaching is a self-contradition and even a deception.  It holds our something which has no reality.  If there is no sending, the preaching of Christ is propaganda, not mission."* - G. Freidrich 

```
"So faith comes from hearing, and hearing through the word of Christ." (17)
```


Maybe Israel didn't...

- <answer>BLANK</answer>?(18) - 

- <answer>BLANK</answer>?(19-21) - 
  - Deuteronomy 32:21 - 
  - Isaiah 65:1 - 
  - Isaiah 65:2 - 

