---
title: "A Christian View of Israel"
author: "Peter Hubbard"
date: 08/28/2016
---
#### *Romans 11:1-36*

Anti-Semitism:

##### Summary of Romans 9-11

God's Word to Israel has not failed. 

1. His decisions are beyond our scrutiny. (ch. 9)
2. People are saved by faith. (ch. 10)
3. He will restore Israel. (ch. 11)

**How should Christians view Israel?**

1. Israel has not been <answer>BLANK</answer>. (1-10)
  -**Four Kinds of Evidence**
    - <answer>BLANK</answer> experience - "for I myself am an Israelite" (1b)
    - <answer>BLANK</answer> evidence - "whom He forknew" (2a)
    - <answer>BLANK</answer> example - "the Scripture says of Elijah" (2b-6)
    - <answer>BLANK</answer> explanation - "as it is written" (7-10)
	  	- *"the rest were hardened"*
		  	- Isaiah 29:10 and Deuteronomy 29:4
		  	- Psalm 69:22 - Worldiness
		  	- Spalm 69:23 - Blindness
2. Gentiles should not be <answer>BLANK</answer>. (11-32)
  - Illustration #1 - <answer>BLANK</answer> (16a)
  - Illustration #2 - <answer>BLANK</answer> (16b-24)
    - **Applicaiton (18-24)**
      - Stop <answer>BLANK</answer> - *"do not be arrogant"* (18)
      - Stop <answer>BLANK</answer> - *"do not becomt proud"* (20)
      - Start <answer>BLANK</answer> - *"but fear"* (20)
      - Start <answer>BLANK</answer> - *"note then"* (22)
    - Does this teach you can lose your salvation?
    - Does this teach that every Jewish person will be saved?
      - *"all Israel will be saved"
        - We know this will happen because...
          - God's Word is reliable. (26-28)
          - God's promises are irrevocable. (28-29)
          - God's decisions are impartial. (30-32)
3. God cannot be <answer>BLANK</answer>. (33-36)
  - His ways are <answer>BLANK</answer>. (33)
  - His ways are <answer>BLANK</answer>. (34-35)
  - His ways are <answer>BLANK</answer>. (36)


